# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: run-tests
        name: Run tests
        description: Runs unittest discover to run Python based unit tests
        types: [python]
        language: system
        pass_filenames: false
        entry: python -m unittest discover -qb
        stages: [commit]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]